#!/bin/bash
 
export TEMP=$0
export CMD=$(echo $TEMP| cut -d'_' -f 2)
export ARCH=$1
export DISTRO=debian

# Input
if [ "$ARCH" == "" ]; then
	ARCH=64
fi

if [ "$ARCH" == "64" ]; then
	QMAKE=/opt/Qt/$QT_VERSION/gcc_64/bin/qmake
fi

# Start
echo $QMAKE $PWD
$QMAKE 4_config.pro
echo

# 3rd Party
cd 0_cppnetlib
echo $CMD $ARCH
source $CMD $ARCH
echo
cd ..

cd 0_cryptopp
echo $CMD $ARCH
source $CMD $ARCH
echo
cd ..

cd 0_msgpack
echo $CMD $ARCH
source $CMD $ARCH
echo
cd ..

# Library
cd 4_core
echo $CMD $ARCH
source $CMD $ARCH
echo
cd ..

cd 4_core_client
echo $CMD $ARCH
source $CMD $ARCH
echo
cd ..

cd 4_core_gui
echo $CMD $ARCH
source $CMD $ARCH
echo
cd ..

# Application
cd 4_client_cli
echo $CMD $ARCH
source $CMD $ARCH
echo
cd ..

cd 4_client_desktop
echo $CMD $ARCH
source $CMD $ARCH
echo
cd ..

cd 4_router_cli
echo $CMD $ARCH
source $CMD $ARCH
echo
cd ..

#echo $CMD $1
#source $CMD $1
#echo
#cd ..
